config/routes.rb
Huginn::Application.routes.draw do
  resources :agents do
    member do
      post :run
      post :dry_run
      post :handle_details_post
      put :leave_scenario
      delete :remove_events
      delete :memory, action: :destroy_memory
    end

    collection do
      post :propagate
      get :type_details
      post :dry_run
      get :event_descriptions
      post :validate
      post :complete
    end

    resources :logs, :only => [:index] do
      collection do
        delete :clear
      end
    end

    resources :events, :only => [:index]
  end

  resource :diagram, :only => [:show]

  resources :events, :only => [:index, :show, :destroy] do
    member do
      post :reemit
    end
  end

  resources :scenarios do
    collection do
      resource :scenario_imports, :only => [:new, :create]
    end

    member do
      get :share
      get :export
    end

    resource :diagram, :only => [:show]
  end

  resources :user_credentials, :except => :show

  resources :services, :only => [:index, :destroy] do
    member do
      post :toggle_availability
    end
  end

  resources :jobs, :only => [:index, :destroy] do
    member do
      put :run
    end
    collection do
      delete :destroy_failed
      delete :destroy_all
    end
  end

  get "/worker_status" => "worker_status#show"

  match "/users/:user_id/web_requests/:agent_id/:secret" => "web_requests#handle_request", :as => :web_requests, :via => [:get, :post, :put, :delete]
  post  "/users/:user_id/webhooks/:agent_id/:secret" => "web_requests#handle_request" # legacy
  post  "/users/:user_id/update_location/:secret" => "web_requests#update_location" # legacy

  devise_for :users,
             controllers: { omniauth_callbacks: 'omniauth_callbacks' },
             sign_out_via: [:post, :delete]
  
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  get "/about" => "home#about"
  root :to => "home#index"
end

app/models/scenario.rb
class Scenario < ActiveRecord::Base
  include HasGuid

  attr_accessible :name, :agent_ids, :description, :public, :source_url, :tag_fg_color, :tag_bg_color

  belongs_to :user, :counter_cache => :scenario_count, :inverse_of => :scenarios
  has_many :scenario_memberships, :dependent => :destroy, :inverse_of => :scenario
  has_many :agents, :through => :scenario_memberships, :inverse_of => :scenarios

  validates_presence_of :name, :user

  validates_format_of :tag_fg_color, :tag_bg_color,
    # Regex adapted from: http://stackoverflow.com/a/1636354/3130625
    :with => /\A#(?:[0-9a-fA-F]{3}){1,2}\z/, :allow_nil => true,
    :message => "must be a valid hex color."

  validate :agents_are_owned

  protected

  def agents_are_owned
    errors.add(:agents, "must be owned by you") unless agents.all? {|s| s.user == user }
  end
end

app/models/user.rb
# Huginn is designed to be a multi-User system.  Users have many Agents (and Events created by those Agents).
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :lockable,
         :omniauthable

  INVITATION_CODES = [ENV['INVITATION_CODE'] || 'try-huginn']

  # Virtual attribute for authenticating by either username or email
  # This is in addition to a real persisted field like 'username'
  attr_accessor :login

  ACCESSIBLE_ATTRIBUTES = [ :email, :username, :login, :password, :password_confirmation, :remember_me, :invitation_code ]

  attr_accessible *ACCESSIBLE_ATTRIBUTES
  attr_accessible *(ACCESSIBLE_ATTRIBUTES + [:admin]), :as => :admin

  validates_presence_of :username
  validates_uniqueness_of :username
  validates_format_of :username, :with => /\A[a-zA-Z0-9_-]{3,15}\Z/, :message => "can only contain letters, numbers, underscores, and dashes, and must be between 3 and 15 characters in length."
  validates_inclusion_of :invitation_code, :on => :create, :in => INVITATION_CODES, :message => "is not valid", if: ->{ User.using_invitation_code? }

  has_many :user_credentials, :dependent => :destroy, :inverse_of => :user
  has_many :events, -> { order("events.created_at desc") }, :dependent => :delete_all, :inverse_of => :user
  has_many :agents, -> { order("agents.created_at desc") }, :dependent => :destroy, :inverse_of => :user
  has_many :logs, :through => :agents, :class_name => "AgentLog"
  has_many :scenarios, :inverse_of => :user, :dependent => :destroy
  has_many :services, -> { by_name('asc') }, :dependent => :destroy

  def available_services
    Service.available_to_user(self).by_name
  end

  # Allow users to login via either email or username.
  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    else
      where(conditions).first
    end
  end

  def self.using_invitation_code?
    ENV['SKIP_INVITATION_CODE'] != 'true'
  end
end

app/controllers/scenarios_controller.rb
class ScenariosController < ApplicationController
  include SortableTable
  skip_before_action :authenticate_user!, only: :export

  def index
    set_table_sort sorts: %w[name public], default: { name: :asc }

    @scenarios = current_user.scenarios.reorder(table_sort).page(params[:page])

    respond_to do |format|
      format.html
      format.json { render json: @scenarios }
    end
  end

  def new
    @scenario = current_user.scenarios.build

    respond_to do |format|
      format.html
      format.json { render json: @scenario }
    end
  end

  def show
    @scenario = current_user.scenarios.find(params[:id])

    set_table_sort sorts: %w[name last_check_at last_event_at last_receive_at], default: { name: :asc }
    @agents = @scenario.agents.preload(:scenarios, :controllers).reorder(table_sort).page(params[:page])

    respond_to do |format|
      format.html
      format.json { render json: @scenario }
    end
  end

  def share
    @scenario = current_user.scenarios.find(params[:id])

    respond_to do |format|
      format.html
      format.json { render json: @scenario }
    end
  end

  def export
    @scenario = Scenario.find(params[:id])
    raise ActiveRecord::RecordNotFound unless @scenario.public? || (current_user && current_user.id == @scenario.user_id)

    @exporter = AgentsExporter.new(:name => @scenario.name,
                                   :description => @scenario.description,
                                   :guid => @scenario.guid,
                                   :tag_fg_color => @scenario.tag_fg_color,
                                   :tag_bg_color => @scenario.tag_bg_color,
                                   :source_url => @scenario.public? && export_scenario_url(@scenario),
                                   :agents => @scenario.agents)
    response.headers['Content-Disposition'] = 'attachment; filename="' + @exporter.filename + '"'
    render :json => JSON.pretty_generate(@exporter.as_json)
  end

  def edit
    @scenario = current_user.scenarios.find(params[:id])

    respond_to do |format|
      format.html
      format.json { render json: @scenario }
    end
  end

  def create
    @scenario = current_user.scenarios.build(params[:scenario])

    respond_to do |format|
      if @scenario.save
        format.html { redirect_to @scenario, notice: 'This Scenario was successfully created.' }
        format.json { render json: @scenario, status: :created, location: @scenario }
      else
        format.html { render action: "new" }
        format.json { render json: @scenario.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @scenario = current_user.scenarios.find(params[:id])

    respond_to do |format|
      if @scenario.update_attributes(params[:scenario])
        format.html { redirect_to @scenario, notice: 'This Scenario was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @scenario.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @scenario = current_user.scenarios.find(params[:id])
    @scenario.destroy

    respond_to do |format|
      format.html { redirect_to scenarios_path }
      format.json { head :no_content }
    end
  end
end

app/helpers/scenario_helper.rb
module ScenarioHelper

  def style_colors(scenario)
    colors = {
      color: scenario.tag_fg_color || default_scenario_fg_color,
      background_color: scenario.tag_bg_color || default_scenario_bg_color
    }.map { |key, value| "#{key.to_s.dasherize}:#{value}" }.join(';')
  end

  def scenario_label(scenario, text = nil)
    text ||= scenario.name
    content_tag :span, text, class: 'label scenario', style: style_colors(scenario)
  end

  def default_scenario_bg_color
    '#5BC0DE'
  end

  def default_scenario_fg_color
    '#FFFFFF'
  end

end

app/views/scenarios/_form.html.erb
<%= form_for(@scenario, :method => @scenario.new_record? ? "POST" : "PUT") do |f| %>
  <% if @scenario.errors.any? %>
    <div class="row well">
      <h2><%= pluralize(@scenario.errors.count, "error") %> prohibited this Scenario from being saved:</h2>
      <% @scenario.errors.full_messages.each do |msg| %>
        <p class='text-warning'><%= msg %></p>
      <% end %>
    </div>
  <% end %>

  <div class="row">
    <div class="col-md-4">
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, :class => 'form-control', :placeholder => "Name your Scenario" %>
      </div>
    </div>
    <div class="col-md-2">
      <div class="form-group">
        <%= f.label :tag_bg_color, "Tag Background Color" %>
        <%= f.color_field :tag_bg_color, :class => 'form-control', :value => @scenario.tag_bg_color || default_scenario_bg_color %>
      </div>
    </div>
    <div class="col-md-2">
      <div class="form-group">
        <%= f.label :tag_fg_color, "Tag Foreground Color" %>
        <%= f.color_field :tag_fg_color, :class => 'form-control', :value => @scenario.tag_fg_color || default_scenario_fg_color %>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-8">
      <div class="form-group">
        <%= f.label :description, "Optional Description" %>
        <%= f.text_area :description, :rows => 10, :class => 'form-control', :placeholder => "Optionally describe what this Scenario will do.  If this will be public, you should also include some contact information." %>
      </div>

      <div class="checkbox">
        <%= f.label :public do %>
          <%= f.check_box :public %> Share this Scenario publicly
        <% end %>
        <span class="glyphicon glyphicon-question-sign hover-help" data-content="When selected, this Scenario and all Agents in it will be made public.  An export URL will be available to share with other Huginn users.  Be very careful that you do not have secret credentials stored in these Agents' options.  Instead, use Credentials by reference."></span>
      </div>

    </div>
  </div>

  <div class="row">
    <div class="col-md-4">
      <div class="form-group">
        <div>
          <%= f.label :agents %>
          <%= f.select(:agent_ids,
                       options_for_select(current_user.agents.pluck(:name, :id), @scenario.agent_ids),
                       {}, { :multiple => true, :size => 5, :class => 'select2 form-control' }) %>
        </div>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-12">
      <div class='form-actions' style='clear: both'>
        <%= f.submit "Save Scenario", :class => "btn btn-primary" %>
      </div>
    </div>
  </div>
<% end %>

app/views/scenarios/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-md-12'>
      <div class="page-header">
        <h2>
          Edit Scenario
        </h2>
      </div>

      <%= render 'form' %>

      <hr>

      <div class="row">
        <div class="col-md-12">
          <%= link_to icon_tag('glyphicon-chevron-left') + ' Back'.html_safe, scenarios_path, class: "btn btn-default" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/scenarios/index.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-md-12'>
      <div class="page-header">
        <h2>
          Your Scenarios
        </h2>
      </div>

      <blockquote>Scenarios are named groups of Agents.  Scenarios allow you to organize your agents,
        and to import and export sets of Agents to share.</blockquote>

      <table class='table table-striped'>
        <tr>
          <th><%= sortable_column 'name', 'asc' %></th>
          <th>Agents</th>
          <th><%= sortable_column 'public' %></th>
          <th></th>
        </tr>

        <% @scenarios.each do |scenario| %>
          <tr>
            <td>
              <%= scenario_label(scenario, content_tag(:i, '', class: 'glyphicon glyphicon-font')) %>
              <%= link_to(scenario.name, scenario) %>
            </td>
            <td><%= link_to pluralize(scenario.agents.count, "agent"), scenario %></td>
            <td><%= scenario.public? ? "yes" : "no" %></td>
            <td>
              <div class="btn-group btn-group-xs" style="float: right">
                <%= link_to 'Show', scenario, class: "btn btn-default" %>
                <%= link_to 'Edit', edit_scenario_path(scenario), class: "btn btn-default" %>
                <%= link_to 'Share', share_scenario_path(scenario), class: "btn btn-default" %>
                <%= link_to 'Delete', scenario_path(scenario), method: :delete, data: { confirm: "This will remove the '#{scenario.name}' Scenerio from all Agents and delete it.  Are you sure?" }, class: "btn btn-default" %>
              </div>
            </td>
          </tr>
        <% end %>
      </table>

      <%= paginate @scenarios, :theme => 'twitter-bootstrap-3' %>

      <br/>

      <div class="btn-group">
        <%= link_to icon_tag('glyphicon-plus') + ' New Scenario'.html_safe, new_scenario_path, class: "btn btn-default" %>
        <%= link_to icon_tag('glyphicon-cloud-upload') + ' Import Scenario'.html_safe, new_scenario_imports_path, class: "btn btn-default" %>
      </div>
    </div>
  </div>
</div>

app/views/scenarios/new.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-md-12'>
      <div class="page-header">
        <h2>
          Create a new Scenario
        </h2>
      </div>

      <%= render 'form' %>

      <hr>

      <div class="row">
        <div class="col-md-12">
          <%= link_to icon_tag('glyphicon-chevron-left') + ' Back'.html_safe, scenarios_path, class: "btn btn-default" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/scenarios/share.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-md-12'>
      <div class="page-header">
        <h2>Share <%= scenario_label(@scenario) %> with the world</h2>
      </div>

      <p>
        <strong>Please be sure that none of the Agents in this Scenario have sensitive data in their settings before sharing!</strong>
      </p>

      <% if @scenario.public? %>
        <p>
          This Scenario is public.  You can <%= link_to "download and share your export file", export_scenario_path(@scenario, :format => :json) %>, or give out this URL:
        </p>

        <form onsubmit='return false;'>
          <input type='text' class='form-control' value='<%= export_scenario_url(@scenario, :format => :json) %>' onclick="return this.select();"/>
        </form>
      <% else %>
        This Scenario is not public.  You can share it by <%= link_to "downloading and sharing your export file", export_scenario_path(@scenario, :format => :json) %>.
      <% end %>

      <hr>

      <div class="row">
        <div class="col-md-12">
          <%= link_to icon_tag('glyphicon-chevron-left') + ' Back'.html_safe, scenario_path(@scenario), class: "btn btn-default" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/scenarios/show.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-md-12'>
      <div class="page-header">
        <h2><%= scenario_label(@scenario) %> <%= "Public" if @scenario.public? %> Scenario</h2>

      </div>

      <% if @scenario.description.present? %>
        <blockquote><%= markdown(@scenario.description) %></blockquote>
      <% end %>

      <%= render 'agents/table', :return_to => scenario_path(@scenario) %>

      <br/>

      <div class="btn-group">
        <%= link_to icon_tag('glyphicon-chevron-left') + ' Back', scenarios_path, class: "btn btn-default" %>
        <%= link_to icon_tag('glyphicon-plus') + ' New Agent', new_agent_path(scenario_id: @scenario.id, return: request.path), class: "btn btn-default" %>
        <%= link_to icon_tag('glyphicon-random') + ' View Diagram', scenario_diagram_path(@scenario), class: "btn btn-default" %>
        <%= link_to icon_tag('glyphicon-edit') + ' Edit', edit_scenario_path(@scenario), class: "btn btn-default" %>
        <% if @scenario.source_url.present? %>
          <%= link_to icon_tag('glyphicon-refresh') + ' Update', new_scenario_imports_path(url: @scenario.source_url), class: "btn btn-default" %>
        <% end %>
        <%= link_to icon_tag('glyphicon-share-alt') + ' Share', share_scenario_path(@scenario), class: "btn btn-default" %>
        <%= link_to icon_tag('glyphicon-trash') + ' Delete', scenario_path(@scenario), method: :delete, data: { confirm: "This will remove the '#{@scenario.name}' Scenerio from all Agents and delete it.  Are you sure?" }, class: "btn btn-default" %>
      </div>
    </div>
  </div>
</div>